# -*- coding: utf-8 -*-

"""
spotifywebapiwithfixesandimprovementsfromsonallux

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from spotifywebapiwithfixesandimprovementsfromsonallux.models.episode_object import EpisodeObject


class ManyEpisodes(object):

    """Implementation of the 'ManyEpisodes' model.

    Attributes:
        episodes (List[EpisodeObject]): The model property of type
            List[EpisodeObject].

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "episodes": 'episodes'
    }

    def __init__(self,
                 episodes=None):
        """Constructor for the ManyEpisodes class"""

        # Initialize members of the class
        self.episodes = episodes 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        episodes = None
        if dictionary.get('episodes') is not None:
            episodes = [EpisodeObject.from_dictionary(x) for x in dictionary.get('episodes')]
        # Return an object of this model
        return cls(episodes)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'episodes={self.episodes!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'episodes={self.episodes!s})')
