# -*- coding: utf-8 -*-

"""
spotifywebapiwithfixesandimprovementsfromsonallux

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class MeFollowingRequest(object):

    """Implementation of the 'Me Following Request' model.

    Attributes:
        ids (List[str]): A JSON array of the artist or user [Spotify
            IDs](/documentation/web-api/concepts/spotify-uris-ids). For
            example: `{ids:["74ASZWbe4lXaubB36ztrGX",
            "08td7MxkoHQkXnWAYD8d6Q"]}`. A maximum of 50 IDs can be sent in
            one request. _**Note**: if the `ids` parameter is present in the
            query string, any IDs listed here in the body will be ignored._

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "ids": 'ids'
    }

    def __init__(self,
                 ids=None):
        """Constructor for the MeFollowingRequest class"""

        # Initialize members of the class
        self.ids = ids 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        ids = dictionary.get("ids") if dictionary.get("ids") else None
        # Return an object of this model
        return cls(ids)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'ids={self.ids!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'ids={self.ids!s})')
