# -*- coding: utf-8 -*-

"""
spotifywebapiwithfixesandimprovementsfromsonallux

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from spotifywebapiwithfixesandimprovementsfromsonallux.models.paging_simplified_album_object import PagingSimplifiedAlbumObject


class PagedAlbums(object):

    """Implementation of the 'PagedAlbums' model.

    Attributes:
        albums (PagingSimplifiedAlbumObject): The model property of type
            PagingSimplifiedAlbumObject.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "albums": 'albums'
    }

    def __init__(self,
                 albums=None):
        """Constructor for the PagedAlbums class"""

        # Initialize members of the class
        self.albums = albums 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        albums = PagingSimplifiedAlbumObject.from_dictionary(dictionary.get('albums')) if dictionary.get('albums') else None
        # Return an object of this model
        return cls(albums)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'albums={self.albums!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'albums={self.albums!s})')
